version: '3'
services:
  tp2back:
    image: 9e4ba5d15d97
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev 
  tp2front:
    image: 80646dee17d5
    ports: 
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1 
